name: test02

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: list1
      run: cmd /c dir /a /s
    - name: build
      run: make
    - name: list2
      run: cmd /c dir /a /s
